name: Build and Test

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run this workflow on pull requests to the 'main' branch!

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fastapi_project_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python 3.14.6
        run: |
          sudo apt update
          sudo apt install -y wget build-essential zlib1g-dev libffi-dev libssl-dev
          wget https://www.python.org/ftp/python/3.14.6/Python-3.14.6.tgz
          tar -xvf Python-3.14.6.tgz
          cd Python-3.14.6
          ./configure
          make
          sudo make install

      - name: Verify Python Version
        run: python3 --version

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo DATABASE_HOSTNAME=localhost >> $GITHUB_ENV
          echo DATABASE_PORT=5432 >> $GITHUB_ENV
          echo DATABASE_USERNAME=postgres >> $GITHUB_ENV
          echo DATABASE_PASSWORD=postgres >> $GITHUB_ENV
          echo DATABASE_NAME=fastapi_project_test >> $GITHUB_ENV

      - name: Run tests
        env:
          DATABASE_HOSTNAME: ${{ env.DATABASE_HOSTNAME }}
          DATABASE_PORT: ${{ env.DATABASE_PORT }}
          DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
        run: pytest